name: Playwright Tests
on:
  push:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: npm install
    - name: Run Playwright tests
      run: npx playwright test
